---
abstract: "Versions of Perl's time functions which work beyond 2038"
author:
  - 'Michael G Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::CBuilder: '0.24'
  JSON: '2.17'
  Module::Build: '0.36'
  Test::Exception: '0.27'
  Test::More: '0.82'
  Test::Warn: '0.11'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.4214, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Time-y2038
provides:
  Time::y2038:
    file: lib/Time/y2038.pm
    version: '20100403'
  Time::y2038::Everywhere:
    file: lib/Time/y2038/Everywhere.pm
    version: '20100403'
requires:
  perl: v5.6.1
resources:
  bugtracker: https://github.com/evalEmpire/y2038/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/evalEmpire/y2038
version: '20100403'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
